"""Add created_at to Order

Revision ID: 69684d73dce2
Revises: b4949d00fae7
Create Date: 2025-03-31 16:26:06.167364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69684d73dce2'
down_revision = 'b4949d00fae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
